### PR TITLE
Hdf5 file support

### PR DESCRIPTION
**Pull request by drowenhorst-nrl**
This provides basic HDF5 file support.  Tested to work with EDAX oh5 files for indexing and NLPAR.  Further testing on Bruker HDF5 is needed.  No current support of Oxford HDF5.

### CODE REVIEW

**Comment by hakonanes** [comment]
It seems to me like this PR moved the Python package into a second directory named `pyebsdindex`, such that `from pyebsdindex import ebsd_index, pcopt` doesn't work anymore. There are duplicates of many files, for example `pyebsdindex/setup.py` and `pyebsdindex/pyebsdindex/setup.py`. Is there a particular reason for this?

**Comment by hakonanes** [comment]
I cannot import modules (which worked before)

```python
>>> from pyebsdindex import ebsd_index, pcopt
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Input In [23], in <module>
----> 1 from pyebsdindex import ebsd_index, pcopt

ImportError: cannot import name 'ebsd_index' from 'pyebsdindex' (unknown location)
>>> from pyebsdindex.pyebsdindex import ebsd_index
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Input In [24], in <module>
----> 1 from pyebsdindex.pyebsdindex import ebsd_index, pcopt

ImportError: cannot import name 'ebsd_index' from 'pyebsdindex' (/home/hakon/kode/pyebsdindex/pyebsdindex/pyebsdindex/__init__.py)
```

or functions

```python
>>> from pyebsdindex.pyebsdindex.ebsd_index as index_pats
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Input In [29], in <module>
----> 1 from pyebsdindex.pyebsdindex.ebsd_index import index_pats

File ~/kode/pyebsdindex/pyebsdindex/pyebsdindex/ebsd_index.py:35, in <module>
     32 import numpy as np
     33 import ray
---> 35 from pyebsdindex import (
     36     band_detect,
     37     band_vote,
     38     ebsd_pattern,
     39     rotlib,
     40     tripletlib,
     41     openclparam
     42 )
     43 from pyebsdindex.EBSDImage import IPFcolor
     46 if ray.__version__ < '1.1.0':  # this fixes an issue when running locally on a VPN

ImportError: cannot import name 'band_detect' from 'pyebsdindex' (unknown location)
```

**Comment by hakonanes** [comment]
OK, I was a bit quick here, everything works as before if I do `pip install --editable .` within `pyebsdindex/pyebsdindex` which then uses `pyebsdindex/pyebsdindex/setup.py` instead of invoking the command to use `pyebsdindex/setup.py`, which was what I'd done previously.

Still, to avoid confusion, I think everything should be moved up a step and remove all the file duplicates.

**Comment by drowenhorst-nrl** [comment]
Oh nuts.  Something goofy is going on.  My local directory structure no longer matches the online repo.  I fear something got messed up with the transition to the public NRL repo.  Git - a blessing and curse all wrapped in three letters.  I will see if I can get it sorted.

**Comment by hakonanes** [comment]
Hah, you're not wrong!

**Pull request merged**
