### PR TITLE
Bug repair

### PR DESCRIPTION
**Pull request by drowenhorst-nrl**
- Hopefully fix issues when using smaller GPUs for NLPAR
- Fix issue when user sends patterns in as Dask arrays (or other non-numpy arrays) to be indexed.  May make an additional copy of the data.

### CODE REVIEW

**Comment by drowenhorst-nrl** [comment]
Please check for compatibility with kikuchipy 0.9.0

**Review by hakonanes — APPROVED** [review]
Your changes here fix my issue reported in https://github.com/pyxem/kikuchipy/issues/675 on my M-series Mac. I've also pulled this branch in GitHub CI to test on the other platforms (https://github.com/pyxem/kikuchipy/pull/676), and all tests pass. Thanks a bunch!

Is your intention then to release a 0.3.1 patch in the near future?

**Comment by drowenhorst-nrl** [comment]
Will actually be a 0.3.2 ... but yeah. Plan on releasing that tomorrow, will be conda-forge probably by Monday (noticed they have been a bit slower recently).

**Comment by hakonanes** [comment]
I'll take a 0.3.2 release as well.

If you find the conda-forge bot slow to respond, we can update the feedstock ourselves: https://conda-forge.org/docs/maintainer/updating_pkgs/#example-workflow-for-updating-a-package. The few times I've updated the feedstock manually, I've just
1. Updated the version and corresponding checksum
2. Updated dependencies if necessary
3. Opened a PR
4. Asked for a re-render by @mentioning in a comment

**Pull request merged**
