### PR TITLE
Improve API reference, update installation guide, rename user guide to tutorials

### LINKED ISSUE #28: Initial non-prerelease version
Should we make a 0.1.0 release?

PyEBSDIndex had to be released with a release candidate (RC) label (`conda install -c conda-forge/label/pyebsdindex_rc pyebsdindex`) since the package isn't available from PyPI without the "rc" label yet. A non-prerelease version should be made available on PyPI so that installation from Anaconda can be done with `conda install -c conda-forge pyebsdindex`.

Instead of using the MAJOR.MINOR.PATCH versioning scheme ([SemVer](https://semver.org/), semantic versioning, example: [NumPy's changelog](https://numpy.org/doc/1.23/release.html)), which states that API incompatible changes can only be included in MAJOR versions, one could use calendar versioning ([CalVer](https://calver.org/), example: [Dask's changelog](https://docs.dask.org/en/stable/changelog.html)). In general, it's OK to release API incompatible changes in MINOR versions while still being a MAJOR-0 package, although one shouldn't have too many of those. With calendar versioning, that requirement isn't possible and in general anything goes, as far as I can tell.

### PR DESCRIPTION
**Pull request by hakonanes**
* Improve API reference. Some parameter names are changed or removed, see the changelog for those. I've made some functions private (adding a starting underscore) to clearly identify private functionality.
* Update installation guide with latest options using Anaconda.
* Rename user guide to "Tutorials". This is in the spirit of the [Diátaxis documentation framework](https://diataxis.fr/), which is followed by e.g. NumPy, Matplotlib, and [kikuchipy](https://kikuchipy.org/en/latest/index.html#learning-resources).

@drowenhorst-nrl: The improved docs can be inspected [here](https://folk.ntnu.no/hakonwii/files/pyebsdindex_doc_demo/_build/html/). Such a docs preview should ideally be [built from every PR](https://docs.readthedocs.io/en/stable/pull-requests.html#configuration) by Read the Docs themselves: to enable this, I believe you have to create a Read the Docs account so I can add you as a [maintainer of the docs](https://readthedocs.org/projects/pyebsdindex/).

Closes #28.

### CODE REVIEW

**Comment by drowenhorst-nrl** [comment]
I have some changes that I made to your PR for updating the tutorial notebooks to match the new API.  Not sure if I am doing that right - do I need permissions to your personal fork?

**Comment by hakonanes** [comment]
That’s great. You should be able to push to my fork, yes.

**Comment by drowenhorst-nrl** [comment]
@hakonanes Hmm - still getting a error "remote: Permission to hakonanes/PyEBSDIndex.git denied to drowenhorst-nrl." This website indicates (at the very end) that you might need to alter the PR?

**Comment by hakonanes** [comment]
Weird, that box is checked. I’ve given you access to my fork, please let me know if the error persist.

**Comment by drowenhorst-nrl** [comment]
Bah - that was my fault of course.  Grabbed your remote with HTTPS, but all my authentication to git hub is ssh.  Changed the URL to a ssh connection and all was good.  Sorry for the confusion.

**Review by drowenhorst-nrl — APPROVED** [review]

**Comment by hakonanes** [comment]
> @drowenhorst-nrl: The improved docs can be inspected [here](https://folk.ntnu.no/hakonwii/files/pyebsdindex_doc_demo/_build/html/). Such a docs preview should ideally be [built from every PR](https://docs.readthedocs.io/en/stable/pull-requests.html#configuration) by Read the Docs themselves: to enable this, I believe you have to create a Read the Docs account so I can add you as a [maintainer of the docs](https://readthedocs.org/projects/pyebsdindex/).

Would you consider making an RTD account?

**Comment by drowenhorst-nrl** [comment]
Done.  drowenhorst-nrl account at RTD.

**Comment by hakonanes** [comment]
Great! As long as you have connected your GitHub account to this RTD account (on RTD, should be under Settings/Admin/Connected Services), we should start to get doc builds from PRs and automatic builds of "latest" whenever `main` is updated.

**Pull request merged**
