### PR TITLE
Post 0.1rc1 release updates

### PR DESCRIPTION
**Pull request by hakonanes**
* Now that PyEBSDIndex is available on PyPI, I've added a badge to the README.
* Add a release guide with all necessary steps.
* Bump version from 0.1rc1 to 0.1.dev0, part of common practice post-release (a step in the release guide).
* Remove `jupyterlab` from list of dependencies in `setup.py`, as no functionality depends on it. Users who only use PyEBSDIndex from scripts don't need it. Users who want to use PyEBSDIndex via Jupyter notebooks can install this separately. I can revert this commit if you want all users to get jupyterlab when installing PyEBSDIndex, @drowenhorst-nrl.
* Add myself to list of contributors `__credits__` in `pyebsdindex/__init__.py`

Feel free to push commits directly to my branch if you want any changes, @drowenhorst-nrl.

### CODE REVIEW

**Comment by drowenhorst-nrl** [comment]
@hakonanes do you need to enable write permissions to your branch for me to edit the PR?  Or am I doing this wrong?

**Comment by hakonanes** [comment]
I believe you should be able to fetch my branch locally, check it out, make commits, and push to my branch as per this box ticked in this PR

bilde

You should be able to do this with

```bash
> git remote add hakonanes git@github.com:hakonanes/PyEBSDIndex.git
> git fetch hakonanes
> git switch -c post-0.1rc1-release-updates hakonanes/post-0.1rc1-release-updates # Last part sets upstream
# Make som changes, add, commit
> git branch -vv # Check upstream, should have the following in the list:
* 0.1rc1-release-updates ac0661c [hakonanes/0.1rc1-release-updates] Expand contributor list to two
> git push
```

**Comment by drowenhorst-nrl** [comment]
Strange - that is what I thought I did, but now went through.  Just some additional instructions in the ReadMe

**Comment by hakonanes** [comment]
Strange indeed. Thanks for merging.

**Pull request merged**
