### PR TITLE
Add simple pytest tests and GitHub CI Actions

### PR DESCRIPTION
**Pull request by hakonanes**
I hope `PyEBSDIndex` can be released on PyPI in the near future (?).

To depend upon it (confidently) in kikuchipy, I'd for it to be tested on continuous integration (CI) servers hosted by GitHub, so that we know that public API performs as expected with new changes, and that bugs are caught before release. I've added four naive tests on a simulated test pattern of Al that's included in the `pyebsdindex/tests/data` directory: we can use another pattern of known phase, detector-sample geometry and orientation, if desired.

The free GitHub CI Actions are set up to run on Ubuntu, macOS and Windows with Python 3.8 and 3.9 on every commit to `main` and to a PR. The Windows checks are failing since pyopencl cannot be installed correctly; not sure why.

Many warnings were raised by pytest when running the tests locally, these have been handled: mainly `np.int` -> `np.int64` and `np.long` -> `np.compat.long`, as suggested by the warnings.

One can now install test dependencies with `pip install -e .[tests]`, which is done in the GitHub CI actions.

### CODE REVIEW

**Comment by hakonanes** [comment]
Turns out it isn't simple to [install `pyopencl`](https://documen.tician.de/pyopencl/misc.html#installation) on Windows from `pip`, only from `conda-forge`, and that the errors in the GitHub CI checks on Windows reflect what a user on Windows will experience when they do `pip install -e .` when trying to install `pyebsdindex`.

**Comment by drowenhorst-nrl** [comment]
It looks like at this point the solution is to just skip Windows on the test builds?  The whole OpenCL environment is tricky.  I was finding issues with the getting the correct ICD files in the right places between macOS and Ubuntu using conda-forge, but I think PyPI handles them a bit better.  Windows is a whole other thing ... partially because I think Windows does not necessarily have openCL installed by default?

**Comment by hakonanes** [comment]
> It looks like at this point the solution is to just skip Windows on the test builds?

Yes, I'll make the CI run fine on macOS and Ubuntu, leaving Windows for another time.

PyEBSDIndex installing fine on Windows as well is a necessity for kikuchipy to depend on PyEBSDIndex, so this is something for me to figure out.

> The whole OpenCL environment is tricky.

Is it possible to make PyOpenCL an optional dependency? One can check whether it's installed or not in the code, and fall back to a CPU implementation when the GPU kernel isn't available? If you could give me some pointers, I could perhaps look at this.

**Comment by hakonanes** [comment]
Tests now pass (see [here](https://github.com/hakonanes/PyEBSDIndex/actions/runs/1843403581) if they aren't to be run in this repo).

**Comment by drowenhorst-nrl** [comment]
Regarding making pyopencl optional ... that is going to take some significant restructuring of the code, but something that I have been thinking about doing even before this.  At the time I first wrote it, it was not clear within band_find that I would have to exit the GPU, and continue processing on the CPU, nor when it was alway advantageous to run on the GPU.  After many twists and turns, I ended being able to put the entire pipeline on the GPU for band_find, but maintained an identical CPU pipeline,  but it is all intertwined in the code.  Thus - I would like to pull the GPU and CPU pipelines apart. I would like to keep them all as one class - just two different methods for that class - but not sure if that is possible for a conditional import (pyopencl)? 

Then there is the initial setup of the GPU queues for the distributed (multi-process) indexing.  It is going to take a bit to make it completely independent.

**Pull request merged**
